### ISSUE TITLE
Develop preprocessing script for legislation from South Africa

### ISSUE THREAD

**Issue by danpdraper** [danpdraper/eia#41]

**Comment by Skyrolon** [comment]
@danpdraper Can you take a look at Article 1 of this legislation and give me some direction on how you would like this to be formatted? 

I don't know why they are tagging on section references to the end of each section (i.e. (xvii)) and this looks quite confusing when preprocessed, as there are no line breaks and the roman numeral from the end of a section ends up beside the roman numeral at the start of the next section (i.e. (xix) (xv)).

**Comment by danpdraper** [comment]
I suspect that the Roman numerals at the end of each paragraph are actually a reference to the equivalent paragraph in the Afrikaans version of the legislation. As the paragraphs in article 1 are arranged alphabetically, the order of those paragraphs would differ in the Afrikaans version. For instance, according to Google Translate, "disposal site" (paragraph vii in the English legislation) is "stortingsterrein" in Afrikaans and it's reasonable to expect that this word would appear near the bottom of a list sorted alphabetically (it is the second-to-last word/phrase in the list according to the Roman numeral at the end of the "disposal site" paragraph). Assuming this is correct, the Roman numerals at the end of the paragraphs do not concern the content of the English legislation and can be removed.

**Comment by Skyrolon** [comment]
Thanks for the clarification. That's a very interesting feature that I had no idea about. I will remove them.
